---
- name: '[Build Image] Get updated files from git repository'
  git:
    repo: "https://{{ DOCKERFILE_GIT_URL }}"
    dest: "{{ DOWNLOAD_PATH }}/{{ SERVICE_NAME }}"
    accept_hostkey: yes

- name: '[Download Artifact] Download artifacts from Nexus'
  get_url:
    url: "http://192.168.20.118:8081/#browse/browse:maven-releases:org%2Fopenshift%2Fmlbparks%2F1.0"
    url: "{{ NEXUS_BASE_URL }}/#browse/browse:{{ NEXUS_REPOSITORY }}&g={{ ARTIFACT_GROUP }}&a={{ ARTIFACT_ID }}&v={{ ARTIFACT_VERSION }}"
    dest: "{{ DOWNLOAD_PATH }}/{{ SERVICE_NAME }}"
