---
- name: '[Build Image] Get updated files from git repository'
  git:
    repo: "https://{{ DOCKERFILE_GIT_URL }}"
    dest: "{{ DOWNLOAD_PATH }}/{{ SERVICE_NAME }}"
    accept_hostkey: yes

- name: '[Download Artifact] Download artifacts from Nexus'
  get_url:
    url: "http://192.168.20.118:8081/service/rest/repository/browse/maven-releases/org/openshift/mlbparks/1.0/"

    dest: "{{ DOWNLOAD_PATH }}/{{ SERVICE_NAME }}"
